default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: 1234
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: library_development
